### ISSUE TITLE
R packages failing to install

### ISSUE THREAD

**Issue by zkamvar** [rocker-org/r-devel-san#1]
Hi,

I'm not sure if this is an issue with Docker itself or an issue with R or an issue with this image, but I'm trying to use this image to set up a devel environment in which to check my package. I've set up a dockerfile here: https://github.com/zkamvar/poppr-devel-docker and have noticed that several packages fail with this message:

```
system2(file.path(R.home("bin"), "R"), c(if (nzchar(arch)) paste0("--arch=",  : 
  cannot popen ' '/usr/local/lib/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpdLFoWn/file164b981179c'', probable reason 'Cannot allocate memory'
[0m
[91m* removing ‘/usr/local/lib/R/site-library/BH’
```

Do you have any insight on this?

Thank you,
Zhian

**Comment by eddelbuettel** [comment]
Well:

> Cannot allocate memory

Give your docker instance more memory.  If this were a structural issue we would be unable to build our bigger Dockerfiles.  [ That said, Debian is current a little volatile because of the gcc5 transition and the need to rebuild all C++ applications and libraries.  But for just R you should be fine. ]

**Comment by zkamvar** [comment]
So it is as I suspected and is an issue with memory limits on docker hub. Thank you for the quick reply.

**Comment by eddelbuettel** [comment]
It fails on the Docker Hub?  Hm.  I don't think we have hit that.  Maybe that just masks a different issue?

**Comment by zkamvar** [comment]
FWIW, it doesn't fail on my OSX.

**Comment by eddelbuettel** [comment]
In which case it may just be them.  FWIW I also got email about the 'drd' Rocker container not building, but have not yet looked in any detail.
