### ISSUE TITLE
R devel features not available, check R-devel date and version

### ISSUE THREAD

**Issue by jangorecki** [rocker-org/r-devel-san#2]
I'm interested to try new R-devel option in `R CMD check`, the `--ignore-vignettes`.
The image provided by hub.docker seems to not providing that feature, I've also build the dockerfile locally and it also doesn't have that feature.

``` sh
docker run -it --net=host rocker/r-devel-san bash
R CMD check --help
```

So in general I'm interested to see exact date of R-devel and if possible also it's devel version.
Currently R.version still returns date and version numbers of last stable release 3.2.3, not a devel, isn't that an issue for R-devel version?
Maybe there is an issue somewhere in the docker build process which results in using some old caches?

**Comment by eddelbuettel** [comment]
``` sh
edd@max:~$ docker pull rocker/drd
latest: Pulling from rocker/drd
5bffa06a3ddf: Pull complete 
15328ebf91ed: Pull complete 
1627d2ee6a2e: Pull complete 
a224f8249b32: Already exists 
1cfa32d83d36: Already exists 
710d129f5ef8: Already exists 
227a3bab7ecd: Already exists 
d7cac4040819: Already exists 
8809551f14e5: Already exists 
e889bbf7d1cc: Already exists 
cac8fcf95d0c: Already exists 
547f1c479c1a: Already exists 
82253473f812: Already exists 
63373a6d0e38: Already exists 
8b1651d59882: Already exists 
Digest: sha256:fc4d339e005d74265fabca84f063d5ed734282aab909f5865681b5c6962bb612
Status: Downloaded newer image for rocker/drd:latest
edd@max:~$ 
edd@max:~$ docker run --rm -ti rocker/drd /bin/bash                                                                                                                                                                 
root@eb5c67df56b9:/# RD --version
R Under development (unstable) (2016-02-29 r70251) -- "Unsuffered Consequences"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

root@eb5c67df56b9:/# 
```

I think this can be closed.

**Comment by jangorecki** [comment]
Definitely, I was not aware of `drd` image, thanks!

@eddelbuettel any hint how can I track the feature release? The `--ignore-vignettes` option to R CMD check is already in [r-devel NEWS](https://github.com/wch/r-source/blob/1e29325a4fe35251e8ba4494c4219ac984186843/doc/NEWS.Rd#L314) since Apr 2015 but `drd` does not ship it.
