### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by jeroen** [rocker-org/r-devel-san#3]
We can get more verbose output by setting some env vars. Perhaps this makes a better default?

```
ENV UBSAN_OPTIONS print_stacktrace=1
ENV ASAN_OPTIONS malloc_context_size=10:fast_unwind_on_malloc=false
```

I'm still trying to figure out how BDR gets the actual line numbers in there.

**Comment by eddelbuettel** [comment]
That looks useful!   

What do you use these days to tickle it?   My examples in [sanitizers](https://github.com/eddelbuettel/sanitizers)?  Something else?    Does that side need work too?

**Comment by jeroen** [comment]
I add dockerfiles to my repo's which CRAN has complained about and then check build logs on dockerhub for ASAN/UBSAN warnings. For example for curl [dockerfile](https://github.com/jeroenooms/curl/blob/master/docker/r-devel-san/Dockerfile) with [output](https://hub.docker.com/r/jeroenooms/curl/builds/).

**Comment by eddelbuettel** [comment]
Good workflow using the hub for builds.  

It would be good to expand the collection in sanitizers so if/when you have something you can distill out the package would be happy to take it ...

**Comment by eddelbuettel** [comment]
Did you see [this README](http://www.stats.ox.ac.uk/pub/bdr/memtests/README.txt)  by BDR? Maybe

```
setenv ASAN_OPTIONS 'alloc_dealloc_mismatch=0:detect_leaks=0:detect_odr_violation=0'   
setenv ASAN_OPTIONS 'alloc_dealloc_mismatch=0:detect_leaks=0:detect_odr_violation=0'   
```

for clang and gcc6, respectively, which appear to be identical...   

He also uses newer compilers which I may not the time to create a setup for....

**Comment by eddelbuettel** [comment]
I made two small commits updating the Dockerfile. 

A better bet may to also try gcc/g++ 6.\* which becoming standard in Debian unstable anyway.

**Comment by eddelbuettel** [comment]
I have now updated the Dockerfile to what BDR has on the README within the memtests directory.  Maybe you can give that a spin.

**Comment by jeroen** [comment]
Ahhh I get now why I am not seeing memory leaks anymore. BDR has disabled these in `ASAN_OPTIONS`. I had not noticed this before. That's unfortunate, those were very useful. He probably disabled them because it reveals too many memleaks in base R.

**Comment by eddelbuettel** [comment]
Thanks for the follow-up here; much appreciated.  

Was thinking the other day about this when I saw a `docker/` subdir in one of your repos.  You are still using this for some / many / ... of your (larger) packages?

**Comment by jeroen** [comment]
Yes I use this image for UBSAN testing of C/C++ code before submitting to CRAN. We also [added it to r-hub](https://builder.r-hub.io/advanced) but that is still very experimental as Gabor is fixing 100 other things first.

**Comment by eddelbuettel** [comment]
I actually saw that at r-hub the other day (when I was hoping to find OS X and/or Windows builders there).

I guess this issue can be closed though?   Do report possibly fixes, improvements, whatnots, ... though.  Oxford is not shouting at me much these days so I don't use this much ;-)

**Comment by jeroen** [comment]
Yeah maybe I'll submit another image just for mem leak testing of packages. But for now I guess I'll just set the `ASAN_OPTIONS` var before testing
