### ISSUE TITLE
Is r-devel-san preferred for current memtest issues on CRAN?

### ISSUE THREAD

**Issue by kylebaron** [rocker-org/r-devel-san#4]
Thanks for putting this docker container together.  It has been very helpful to me.

__Is `r-devel-san` your preferred setup for reproducing memtest issues on CRAN__?  It is running for me, but unfortunately I can't reproduce my issue.  __Not__ asking for help to troubleshoot that ... just want to make sure I'm running on the best rocker option.  I also looked at` r-devel-ubsan-clang` but can't get that one to run.

Thanks.

[edited]

**Comment by eddelbuettel** [comment]
It's messy.   

As far as I know, the CRAN checks are on some highly customized machines / setups put together by Brian Ripley.   On a recent upload of mine, I stated that I was unable to replicate their ASAN / UBSAN issues simply relying on [the corresponding R Hub builder](https://builder.r-hub.io/) -- and Vienna concurred.

Now, @gaborcsardi said he'd have a PR for the Docker container for an update but I have not heard.

Lastly, one other concern is that the regularly scheduled builds on the ASAN/UBSAN containers ... fails each time on a spurious timeout.  @cboettig, time to turn those builds off?  Thoughts?

**Comment by kylebaron** [comment]
@eddelbuettel Thanks.  Check comes back clean on both `rocker/r-devel-san` and `rhub::check_with_sanitizers`.  

And thanks for "spamming" R devel back in 2015 and getting all of this started.  I wouldn't stand a chance without these tools and all the blog posts providing help.

**Comment by eddelbuettel** [comment]
Thanks -- meant to mention the blog posts. This all was put together so that we could indeed more easily duplicate what "they" see.   But there always is some drift between the setups so ...  _shrugs_ ... we can only try to catch up with PRs as needed.

**Comment by cboettig** [comment]
@eddelbuettel agreed. I've just turned off the cron job triggers for those `san` & `ubsan` containers.
