### ISSUE TITLE
Fatal error: you must specify '--save', '--no-save' or '--vanilla'

### ISSUE THREAD

**Issue by xgdgsc** [rocker-org/r-devel-san#5]
Hi, trying to reproduce an san error that received warning of retain package email from Prof Ripley here.

When I build image with this Dockerfile and run
 `docker run --name rsan  rsan `
I get                                                     
`Fatal error: you must specify '--save', '--no-save' or '--vanilla'`
I looked through the Dockerfile and didn't find anything related. Any clues?

**Comment by eddelbuettel** [comment]
What is that command supposed to do?

Have you worked with Docker before?  Have you looked at some tutorials?  Or blog posts?

The error messages is standard R when invoked the _wrong_ way:

```sh
edd@rob:~$ echo '2+2' | R
Fatal error: you must specify '--save', '--no-save' or '--vanilla'
edd@rob:~$ 
```

My website, among other places, has some (older) writeups of how one can use the container. Can you please take a look there?   Major tip: you want `RD`, `R`, for this. 

If and when you find an actual error in the container, feel free to reopen.  You can also use RHub to test for ASAN/SAN behavior.  The whole process is tricky, also see old mails on the r-package-devel list.  Good luck!
